modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"
mixins="optivex.mixins.json"

[[mods]]
modId="optivex"
version="${mod_version}"
displayName="Optivex"
authors="Mica_team"
description='''
Optivex is a lightweight Minecraft performance optimization mod.
'''

[[dependencies.optivex]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.optivex]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
