modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
modId="optivex"
version="${file.jarVersion}"
displayName="Optivex"
authors="Mica-team"
description='''
Optivex is a lightweight Minecraft performance optimization mod
designed to improve FPS, reduce unnecessary CPU usage, and optimize
game performance without changing the vanilla gameplay experience.
'''

[[dependencies.optivex]]
modId="forge"
mandatory=true
versionRange="[47.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.optivex]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
